spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/db_gdms?characterEncoding=utf8
    username : root
    password : javaee

logging:
  level:
    com:
      fhx:
        gdms: DEBUG
debug:
  true