spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/db_gdms?characterEncoding=utf8
    username : root
    password : javaee
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

logging:
  level:
    com:
      fhx:
        gdms: DEBUG
debug:
  true